# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9c137875e8d2f8ad3e48159d18cd8392c8971942c9d0cd722f81b26d1b218fd16a292bdaa4729381d7ec89d7d08743c485a1134c7ca33b124c1a0d10209a951

test:
  secret_key_base: 2efa45c51ae0df59382d2b8c0a4947b3d5d2c22fdc9de3145488d23b7095513b4013ac1524ba0dada4884ec07bc4ec92bff8c48e858376da6ece81a59bc58088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
